name: Publish to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "packages/*/docs/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Generate Site
        run: pnpx antora docs/antora-playbook.yml
      - name: Copy redirect index.html
        run: sudo cp docs/index.html docs/build/site
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/site
